Repository exercism/cfml, pull requests merged in 2024-04, with the labels that each got.

#253 Add collatz-conjecture
  config.json
  exercises/practice/collatz-conjecture/.docs/instructions.md
  exercises/practice/collatz-conjecture/.meta/Example.cfc
  exercises/practice/collatz-conjecture/.meta/ExampleTest.cfc
  exercises/practice/collatz-conjecture/.meta/config.json
  exercises/practice/collatz-conjecture/.meta/tests.toml
  exercises/practice/collatz-conjecture/CollatzConjecture.cfc
  exercises/practice/collatz-conjecture/CollatzConjectureTest.cfc
  exercises/practice/collatz-conjecture/TestRunner.cfc
  exercises/practice/collatz-conjecture/box.json
  exercises/practice/collatz-conjecture/index.cfm
Labels: x:module/practice-exercise, x:rep/medium

#255 Rename CLIRenderer@testbox-commands as CLIRenderer@testbox-cli
  exercises/practice/acronym/TestRunner.cfc
  exercises/practice/all-your-base/TestRunner.cfc
  exercises/practice/allergies/TestRunner.cfc
  exercises/practice/anagram/TestRunner.cfc
  exercises/practice/atbash-cipher/TestRunner.cfc
  exercises/practice/binary-search/TestRunner.cfc
  exercises/practice/bob/TestRunner.cfc
  exercises/practice/circular-buffer/TestRunner.cfc
  exercises/practice/darts/TestRunner.cfc
  exercises/practice/diamond/TestRunner.cfc
  exercises/practice/difference-of-squares/TestRunner.cfc
  exercises/practice/dnd-character/TestRunner.cfc
  exercises/practice/eliuds-eggs/TestRunner.cfc
  exercises/practice/etl/TestRunner.cfc
  exercises/practice/flatten-array/TestRunner.cfc
  exercises/practice/gigasecond/TestRunner.cfc
  exercises/practice/grains/TestRunner.cfc
  exercises/practice/hamming/TestRunner.cfc
  exercises/practice/hello-world/TestRunner.cfc
  exercises/practice/isogram/TestRunner.cfc
  exercises/practice/largest-series-product/TestRunner.cfc
  exercises/practice/leap/TestRunner.cfc
  exercises/practice/list-ops/TestRunner.cfc
  exercises/practice/luhn/TestRunner.cfc
  exercises/practice/markdown/TestRunner.cfc
  exercises/practice/nth-prime/TestRunner.cfc
  exercises/practice/nucleotide-count/TestRunner.cfc
  exercises/practice/pangram/TestRunner.cfc
  exercises/practice/perfect-numbers/TestRunner.cfc
  exercises/practice/pig-latin/TestRunner.cfc
  exercises/practice/protein-translation/TestRunner.cfc
  exercises/practice/queen-attack/TestRunner.cfc
  exercises/practice/raindrops/TestRunner.cfc
  exercises/practice/resistor-color-duo/TestRunner.cfc
  exercises/practice/resistor-color/TestRunner.cfc
  exercises/practice/reverse-string/TestRunner.cfc
  exercises/practice/rna-transcription/TestRunner.cfc
  exercises/practice/robot-simulator/TestRunner.cfc
  exercises/practice/roman-numerals/TestRunner.cfc
  exercises/practice/run-length-encoding/TestRunner.cfc
  exercises/practice/saddle-points/TestRunner.cfc
  exercises/practice/scrabble-score/TestRunner.cfc
  exercises/practice/secret-handshake/TestRunner.cfc
  exercises/practice/space-age/TestRunner.cfc
  exercises/practice/square-root/TestRunner.cfc
  exercises/practice/strain/TestRunner.cfc
  exercises/practice/sum-of-multiples/TestRunner.cfc
  exercises/practice/triangle/TestRunner.cfc
  exercises/practice/two-fer/TestRunner.cfc
  exercises/practice/word-count/TestRunner.cfc
  tasks/exercise_template/TestRunner.cfc
Labels: x:rep/tiny

#254 Sync docs and metadata
  exercises/practice/all-your-base/.docs/instructions.md
  exercises/practice/all-your-base/.docs/introduction.md
  exercises/practice/darts/.docs/instructions.md
  exercises/practice/darts/.meta/config.json
  exercises/practice/eliuds-eggs/.meta/config.json
  exercises/practice/flatten-array/.docs/instructions.md
  exercises/practice/hello-world/.meta/config.json
  exercises/practice/queen-attack/.docs/instructions.md
  exercises/practice/raindrops/.meta/config.json
  exercises/practice/scrabble-score/.docs/instructions.md
  exercises/practice/scrabble-score/.docs/introduction.md
  exercises/practice/secret-handshake/.meta/config.json
  exercises/practice/strain/.meta/config.json
Labels: x:action/sync, x:rep/tiny

#256 dnd-character: sync
  exercises/practice/dnd-character/.docs/instructions.md
  exercises/practice/dnd-character/.docs/introduction.md
Labels: x:size/tiny
